---
- name: Update system and reboot if necessary
  hosts: all
  become: yes
  tasks:
    - name: Determine OS distribution
      set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: os_family == "Debian"

    - name: Update RedHat/Fedora systems
      yum:
        name: '*'
        state: latest
      when: os_family == "RedHat"

    - name: Check if a reboot is required for Debian/Ubuntu
      command: /usr/bin/dpkg --get-selections | grep -c '^linux-image'
      register: kernel_count
      changed_when: false
      when: os_family == "Debian"
      become: yes

    - name: Check if a reboot is required for RedHat/Fedora
      command: needs-restarting
      register: reboot_check
      changed_when: false
      when: os_family == "RedHat"
      ignore_errors: yes  # Ignore errors if the command is not found

    - name: Set reboot_required variable for RedHat/Fedora
      set_fact:
        reboot_required_flag: true
      when: reboot_check is defined and reboot_check.rc == 1

    - name: Reboot the system if required for Debian/Ubuntu
      reboot:
      when: kernel_count.stdout|int > 0

    - name: Reboot the system if required for RedHat/Fedora
      reboot:
      when: reboot_required_flag | default(false)  # Default to false if not set
